// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
void HideBtn_Animation(lv_obj_t * TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Home_Scr
void ui_Home_Scr_screen_init(void);
extern lv_obj_t * ui_Home_Scr;
extern lv_obj_t * ui_ButtonPanelTest1;
void ui_event_StockMarketButton(lv_event_t * e);
extern lv_obj_t * ui_StockMarketButton;
extern lv_obj_t * ui_CasinoLabel1;
void ui_event_CasinoButton(lv_event_t * e);
extern lv_obj_t * ui_CasinoButton;
extern lv_obj_t * ui_CasinoLabel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_bigarcr;
extern lv_obj_t * ui_bigarcl;
extern lv_obj_t * ui_midarcr;
extern lv_obj_t * ui_midarcl;
extern lv_obj_t * ui_smallarcr;
extern lv_obj_t * ui_smallarcl;
// CUSTOM VARIABLES
extern lv_obj_t * uic_midarc;

// SCREEN: ui_StocksScreen
void ui_StocksScreen_screen_init(void);
extern lv_obj_t * ui_StocksScreen;
extern lv_obj_t * ui_Chart1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_CasinoScreen
void ui_CasinoScreen_screen_init(void);
extern lv_obj_t * ui_CasinoScreen;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Roller3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_tesla_png);    // assets/tesla.png
LV_IMG_DECLARE(ui_img_arc_big_png);    // assets/arc_big.png
LV_IMG_DECLARE(ui_img_arc_mid_png);    // assets/arc_mid.png
LV_IMG_DECLARE(ui_img_arc_small_png);    // assets/arc_small.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_FontStocks);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
