// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"

void btn_clicked(lv_event_t *e)
{
    // Your code here
}
