// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_CasinoScreen_screen_init(void)
{
    ui_CasinoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CasinoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_CasinoScreen);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -5);
    lv_obj_set_y(ui_Button7, -108);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "HOME");

    ui_Button1 = lv_btn_create(ui_CasinoScreen);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 104);
    lv_obj_set_y(ui_Button1, 91);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SPIN");

    ui_Roller3 = lv_roller_create(ui_CasinoScreen);
    lv_roller_set_options(ui_Roller3, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roller3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roller3, -104);
    lv_obj_set_y(ui_Roller3, 16);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
