// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x4A484A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_Panel7, 142);
    lv_obj_set_height(ui_Panel7, 292);
    lv_obj_set_x(ui_Panel7, 104);
    lv_obj_set_y(ui_Panel7, 1);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xE0DA93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_Panel1, 142);
    lv_obj_set_height(ui_Panel1, 52);
    lv_obj_set_x(ui_Panel1, 100);
    lv_obj_set_y(ui_Panel1, 71);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xA8707D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_Panel2, 142);
    lv_obj_set_height(ui_Panel2, 52);
    lv_obj_set_x(ui_Panel2, 102);
    lv_obj_set_y(ui_Panel2, -77);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xA8707D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_teslamain = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_teslamain, &ui_img_tesla_png);
    lv_obj_set_width(ui_teslamain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_teslamain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_teslamain, -68);
    lv_obj_set_y(ui_teslamain, -19);
    lv_obj_set_align(ui_teslamain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_teslamain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_teslamain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bigarcr = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_bigarcr, &ui_img_arc_big_2_png);
    lv_obj_set_width(ui_bigarcr, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_bigarcr, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_bigarcr, -6);
    lv_obj_set_y(ui_bigarcr, 66);
    lv_obj_set_align(ui_bigarcr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bigarcr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bigarcr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_bigarcr, 1450);
    lv_obj_set_style_outline_color(ui_bigarcr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_bigarcr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bigarcl = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_bigarcl, &ui_img_arc_big_2_png);
    lv_obj_set_width(ui_bigarcl, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_bigarcl, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_bigarcl, -129);
    lv_obj_set_y(ui_bigarcl, 65);
    lv_obj_set_align(ui_bigarcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bigarcl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bigarcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_bigarcl, -1450);

    ui_midarcr = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_midarcr, &ui_img_arc_mid_2_png);
    lv_obj_set_width(ui_midarcr, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_midarcr, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_midarcr, -12);
    lv_obj_set_y(ui_midarcr, 56);
    lv_obj_set_align(ui_midarcr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_midarcr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_midarcr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_midarcr, 1450);

    ui_midarcl = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_midarcl, &ui_img_arc_mid_2_png);
    lv_obj_set_width(ui_midarcl, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_midarcl, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_midarcl, -123);
    lv_obj_set_y(ui_midarcl, 55);
    lv_obj_set_align(ui_midarcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_midarcl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_midarcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_midarcl, -1450);

    ui_smallarcr = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_smallarcr, &ui_img_arc_small_2_png);
    lv_obj_set_width(ui_smallarcr, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_smallarcr, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_smallarcr, -19);
    lv_obj_set_y(ui_smallarcr, 46);
    lv_obj_set_align(ui_smallarcr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smallarcr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_smallarcr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_smallarcr, 1450);

    ui_smallarcl = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_smallarcl, &ui_img_arc_small_2_png);
    lv_obj_set_width(ui_smallarcl, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_smallarcl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_smallarcl, -116);
    lv_obj_set_y(ui_smallarcl, 44);
    lv_obj_set_align(ui_smallarcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smallarcl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_smallarcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_smallarcl, -1450);

    ui_barricade1 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_barricade1, 10);
    lv_obj_set_height(ui_barricade1, 238);
    lv_obj_set_x(ui_barricade1, 32);
    lv_obj_set_y(ui_barricade1, 2);
    lv_obj_set_align(ui_barricade1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_barricade1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_barricade1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barricade1, lv_color_hex(0x5A1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barricade1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barricade1, lv_color_hex(0x9C0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barricade1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_teslaLight = lv_img_create(ui_Home_Scr);
    lv_obj_set_width(ui_teslaLight, LV_SIZE_CONTENT);   /// 145
    lv_obj_set_height(ui_teslaLight, LV_SIZE_CONTENT);    /// 101
    lv_obj_set_x(ui_teslaLight, -71);
    lv_obj_set_y(ui_teslaLight, -19);
    lv_obj_set_align(ui_teslaLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_teslaLight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_teslaLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_barricade2 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_barricade2, 337);
    lv_obj_set_height(ui_barricade2, 12);
    lv_obj_set_x(ui_barricade2, 4);
    lv_obj_set_y(ui_barricade2, 119);
    lv_obj_set_align(ui_barricade2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_barricade2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_barricade2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barricade2, lv_color_hex(0x5A1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barricade2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barricade2, lv_color_hex(0x9C0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barricade2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barricade3 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_barricade3, 337);
    lv_obj_set_height(ui_barricade3, 12);
    lv_obj_set_x(ui_barricade3, 6);
    lv_obj_set_y(ui_barricade3, -121);
    lv_obj_set_align(ui_barricade3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_barricade3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_barricade3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barricade3, lv_color_hex(0x581717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barricade3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barricade3, lv_color_hex(0x9C0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barricade3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barricade4 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_barricade4, 10);
    lv_obj_set_height(ui_barricade4, 238);
    lv_obj_set_x(ui_barricade4, 161);
    lv_obj_set_y(ui_barricade4, 1);
    lv_obj_set_align(ui_barricade4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_barricade4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_barricade4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barricade4, lv_color_hex(0x5A1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barricade4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barricade4, lv_color_hex(0x950D02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barricade4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barricade5 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_barricade5, 10);
    lv_obj_set_height(ui_barricade5, 238);
    lv_obj_set_x(ui_barricade5, -161);
    lv_obj_set_y(ui_barricade5, -3);
    lv_obj_set_align(ui_barricade5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_barricade5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_barricade5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barricade5, lv_color_hex(0x5A1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barricade5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barricade5, lv_color_hex(0x9A0F07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barricade5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CasinoButton = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_CasinoButton, 100);
    lv_obj_set_height(ui_CasinoButton, 131);
    lv_obj_set_x(ui_CasinoButton, 96);
    lv_obj_set_y(ui_CasinoButton, -2);
    lv_obj_set_align(ui_CasinoButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_CasinoButton, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CasinoButton, lv_color_hex(0x932424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CasinoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CasinoButton, lv_color_hex(0x603939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CasinoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CasinoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CasinoButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CasinoLabel = lv_label_create(ui_CasinoButton);
    lv_obj_set_width(ui_CasinoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CasinoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CasinoLabel, -1);
    lv_obj_set_y(ui_CasinoLabel, 1);
    lv_obj_set_align(ui_CasinoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CasinoLabel, "casino");
    lv_obj_set_style_text_color(ui_CasinoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CasinoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_CasinoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_CasinoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CasinoLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_CasinoLabel, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CasinoLabel, &ui_font_PizzaFontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_CasinoButton, ui_event_CasinoButton, LV_EVENT_ALL, NULL);
    uic_midarc = ui_bigarcr;

}
