// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x4A484A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPanelTest1 = lv_obj_create(ui_Home_Scr);
    lv_obj_set_width(ui_ButtonPanelTest1, 316);
    lv_obj_set_height(ui_ButtonPanelTest1, 57);
    lv_obj_set_x(ui_ButtonPanelTest1, 0);
    lv_obj_set_y(ui_ButtonPanelTest1, -100);
    lv_obj_set_align(ui_ButtonPanelTest1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonPanelTest1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ButtonPanelTest1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_ButtonPanelTest1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonPanelTest1, lv_color_hex(0x8A4747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPanelTest1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonPanelTest1, lv_color_hex(0x4A484A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonPanelTest1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonPanelTest1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StockMarketButton = lv_btn_create(ui_ButtonPanelTest1);
    lv_obj_set_height(ui_StockMarketButton, 77);
    lv_obj_set_width(ui_StockMarketButton, lv_pct(20));
    lv_obj_set_x(ui_StockMarketButton, -141);
    lv_obj_set_y(ui_StockMarketButton, 20);
    lv_obj_set_align(ui_StockMarketButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_StockMarketButton, lv_color_hex(0xD9D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StockMarketButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CasinoLabel1 = lv_label_create(ui_StockMarketButton);
    lv_obj_set_width(ui_CasinoLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CasinoLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CasinoLabel1, 0);
    lv_obj_set_y(ui_CasinoLabel1, 19);
    lv_obj_set_align(ui_CasinoLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CasinoLabel1, "STONKS!");
    lv_obj_set_style_text_color(ui_CasinoLabel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CasinoLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_CasinoLabel1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CasinoLabel1, &ui_font_FontStocks, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CasinoButton = lv_btn_create(ui_ButtonPanelTest1);
    lv_obj_set_height(ui_CasinoButton, 77);
    lv_obj_set_width(ui_CasinoButton, lv_pct(20));
    lv_obj_set_x(ui_CasinoButton, -141);
    lv_obj_set_y(ui_CasinoButton, 20);
    lv_obj_set_align(ui_CasinoButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CasinoButton, lv_color_hex(0xD9D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CasinoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CasinoLabel = lv_label_create(ui_CasinoButton);
    lv_obj_set_width(ui_CasinoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CasinoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CasinoLabel, 0);
    lv_obj_set_y(ui_CasinoLabel, 19);
    lv_obj_set_align(ui_CasinoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CasinoLabel, "Casino");
    lv_obj_set_style_text_color(ui_CasinoLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CasinoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_CasinoLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CasinoLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_Image2, &ui_img_tesla_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bigarcr = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_bigarcr, &ui_img_arc_big_png);
    lv_obj_set_width(ui_bigarcr, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_bigarcr, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_bigarcr, 89);
    lv_obj_set_y(ui_bigarcr, 72);
    lv_obj_set_align(ui_bigarcr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bigarcr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bigarcr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_bigarcr, 1450);
    lv_obj_set_style_outline_color(ui_bigarcr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_bigarcr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bigarcl = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_bigarcl, &ui_img_arc_big_png);
    lv_obj_set_width(ui_bigarcl, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_bigarcl, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_bigarcl, -88);
    lv_obj_set_y(ui_bigarcl, 74);
    lv_obj_set_align(ui_bigarcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bigarcl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bigarcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_bigarcl, -1450);

    ui_midarcr = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_midarcr, &ui_img_arc_mid_png);
    lv_obj_set_width(ui_midarcr, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_midarcr, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_midarcr, 81);
    lv_obj_set_y(ui_midarcr, 63);
    lv_obj_set_align(ui_midarcr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_midarcr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_midarcr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_midarcr, 1450);

    ui_midarcl = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_midarcl, &ui_img_arc_mid_png);
    lv_obj_set_width(ui_midarcl, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_midarcl, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_midarcl, -81);
    lv_obj_set_y(ui_midarcl, 63);
    lv_obj_set_align(ui_midarcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_midarcl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_midarcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_midarcl, -1450);

    ui_smallarcr = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_smallarcr, &ui_img_arc_small_png);
    lv_obj_set_width(ui_smallarcr, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_smallarcr, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_smallarcr, 73);
    lv_obj_set_y(ui_smallarcr, 54);
    lv_obj_set_align(ui_smallarcr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smallarcr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_smallarcr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_smallarcr, 1450);

    ui_smallarcl = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_smallarcl, &ui_img_arc_small_png);
    lv_obj_set_width(ui_smallarcl, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_smallarcl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_smallarcl, -73);
    lv_obj_set_y(ui_smallarcl, 54);
    lv_obj_set_align(ui_smallarcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smallarcl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_smallarcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_smallarcl, -1450);

    lv_obj_add_event_cb(ui_StockMarketButton, ui_event_StockMarketButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CasinoButton, ui_event_CasinoButton, LV_EVENT_ALL, NULL);
    uic_midarc = ui_bigarcr;

}
